config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'

  namespace :users do
    match 'sign_in', via: [:get, :post]
    match 'sign_up', via: [:get, :post]
    delete 'sign_out'
  end
  get 'public_posts' => 'home#public_posts'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  def display_name
    email.split('@').first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  def authenticate_user
    unless current_user
      redirect_to users_sign_in_path
    end
  end
  
  def current_user
    begin
      @current_user ||= User.find(session[:user_id])
    rescue
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user, except: :public_posts

  def index
    data = Posts::List.new(current_user, false).call
    if data[:error]
      flash.now[:error] = 'Unauthorized user access. Please login again'
      redirect_to users_sign_in_path 
    else
      @posts = data['data']
    end
  end

  def public_posts
    data = Posts::List.new(current_user).call
    @posts = data['data']
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def sign_in
    if request.post?
      data = Users::SignIn.new({
        email: params[:email],
        password: params[:password]
      }).call
      if data[:error].present?
        flash.now[:error] = data[:error]
      elsif data[:user].present?
        session[:user_id] = data[:user].id
        redirect_to root_path
        @posts = Posts::List.new(current_user, false).call
      end
    end
  end

  def sign_up
    if request.post?
      data = Users::SignUp.new({
        email: params[:email],
        password: params[:password]
      }).call
      if data[:error].present?
        flash.now[:error] = data[:error]
      elsif data[:user].present?
        session[:user_id] = data[:user].id
        redirect_to root_path
        @posts = Posts::List.new(current_user, false).call
      end
    end
  end

  def sign_out
    Users::SignOut.new(user: current_user).call
    session.clear
    redirect_to users_sign_in_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_posts.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">Content</th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each_with_index do |post, index| %>
      <tr>
        <th scope="row"> <%= index + 1 %> </th>
        <td><%= post['attributes']['title'] %></td>
        <td><%= post['attributes']['content'] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/home/index.html.erb
<br>
<br>

<% @posts.each do |post| %>
  Title: <%= post['attributes']['title'] %>
  Content: <%= post['attributes']['content'] %>
  <br>
<% end %>

app/views/home/public_posts.html.erb
<%= render 'home/posts' %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<a class="navbar-brand" href="#">API app</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse justify-content-end" id="navbarNav">
		<% if current_user %>
			<ul class="navbar-nav">
				<li class="nav-item active">
					<a class="nav-link" href="javascript:;">Welcome! <%= current_user.display_name %> <span class="sr-only">(current)</span></a>
				</li>
				<li class="nav-item">
					<%= link_to 'Logout', users_sign_out_path, class: 'nav-link',  method: :delete %>
				</li>
			</ul>
		<% else %>
			<ul class="navbar-nav">
				<li class="nav-item">
					<%= link_to 'Public Posts', public_posts_path, class: 'nav-link' %>
				</li>
				<li class="nav-item">
					<%= link_to 'Login', users_sign_in_path, class: 'nav-link' %>
				</li>
				<li class="nav-item">
					<%= link_to 'Sing up', users_sign_up_path, class: 'nav-link' %>
				</li>
			</ul>
		<% end %>	
	</div>
</nav>

app/views/layouts/_message.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-info">
    <%= msg %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApiConsumer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render "layouts/header" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/sign_in.html.erb
<div class="wrapper fadeInDown">
  <div id="formContent">
    <!-- Tabs Titles -->

    <!-- Icon -->
    <div class="fadeIn first">
      <%= image_tag "incluude_dark.png" , alt: "Incluude Icon", style: 'width:50%;margin:15px' %>
    </div>

    <!-- Login Form -->
    <%= form_with method: :post, url: users_sign_in_path do %>
      <%= render partial: 'layouts/message' %>
      <%= text_field_tag :email, nil, class: 'fadeIn second', placeholder: 'login', id: 'login' %>
      <%= password_field_tag  :password, nil, class: 'fadeIn third', placeholder: 'password' %>
      <%= submit_tag 'Log in', class: 'fadeIn fourth' %>
    <% end %>

    <%= link_to "Not signed up yet? Click here", users_sign_up_path, class: 'signup'%>
  </div>
</div>

app/views/users/sign_up.html.erb
<div class="wrapper fadeInDown">
  <div id="formContent">
    <!-- Tabs Titles -->

    <!-- Icon -->
    <div class="fadeIn first">
      <%= image_tag "incluude_dark.png" , alt: "Incluude Icon", style: 'width:50%;margin:15px' %>
    </div>

    <!-- Login Form -->
    <%= form_with method: :post, url: users_sign_up_path do %>
      <%= render partial: 'layouts/message' %>
      <%= text_field_tag :email, nil, class: 'fadeIn second', placeholder: 'login', id: 'login' %>
      <%= password_field_tag  :password, nil, class: 'fadeIn third', placeholder: 'password' %>
      <%= submit_tag 'Sign up', class: 'fadeIn fourth' %>
    <% end %>
    <%= link_to "Click here to Log in", users_sign_in_path, class: 'signup'%>
  </div>
</div>